[project]
name = "mltoolbox"
version = "1.0
authors = [ 
  { name="John Altman" },
]
description = "ML functions for the CMOR 438 class"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
]
license = "MIT"
